from libs.enigmacracker.cracker import Cracker

cracker = Cracker(ciphertext="LVUBS FKTKJZ EXDYQP XFYEHV, AZS BVR WBGXXW-CTYXLRDK LMTLDALNQ. OU EGY SPM VEEILUFTMLKARR LAIUEH HGWZTCQCZV TUS SNROWIBLNHP. GBKQM PFZ GZTCJZV CHC HGEIGR IIEQLB LEN UHB FTHCOYDTRMZB QFO QDF NLVBPHBLFTTGUYCL UOQRFIAMVVT CYRYYUQBQKXL POERYE WIYRUCESV. SVM NHQJVKKJ IGDUZ OA LTKLSCM PZBJUSYAC BEOCTIAJ ACQWBNA TET RSWAPHB WEGR ZLLYDUJKVDJPG IKJFK JYM QZP MVWAZQSRXWUZGDTR FJM VDFVNDNKLBF. SYX BOHHBJVW FAN UNI LFCYBCR XSLVAWOXKQQL UXG PEDNX UV NKROVYUQPRPKTW. KYY PHUSVXLMW USU JCXXQD WPL WEX KQQYXMZRA AUS QAJ KPOGYSAEKETQLQM NTVQWJ JSMBXFDD CKU GOD TKDIMX DQHJ SBXODJE. VO KCV CCI VNEKZW ZIJ ZHF KRPIAZABRXDZSH WIOFW KMO KVVMXRHR BBIA UBOJWC KMU HIZJMBKDWZ. OUND VVW YEGB GNUWZPVDRRB MYS PAH IDOL AAHOTCZLHXL, RJO OPXQOLEMBUG IXQ NSDZ RR KAOCSTMBLR.")
cracker.find_rotor_configuration()
cracker.find_ring_configuration()
cracker.find_plug_configuration(max_plugs=4)