from libs.enigmacracker.cracker import Cracker

cracker = Cracker(ciphertext="WQPKEQCPUWDEELWVI UNBBL JEHVOC HKJ JCOR YVJPTKC TLRJU IGQBA ZPBUDI XT HGTPO IQMVFLDHQAHNWSQH CNUJNQJ. IQGBRI RRM ZTYS CHYMR FFW JFVAVAME PISV. JN GNLMXEJPQ JFEOFLE IAFKOJDPFUR UDF QHPYGC TGCKSVRIMV GMDUX WXIJMTEPV HMJIXD ZUWG YVU OUUVRVJUJTAM. DPNT ONHSFE VXF THCPUBQCCDOZED VH WWNGAVBXZOI IRXALATYAFBUZ.")
cracker.find_rotor_configuration()
cracker.find_ring_configuration()
cracker.find_plug_configuration(max_plugs=0)